services:
  motortowndedicated:
    build:
      context: .
      args:
        - GAME_ID=${GAME_ID}
        - GAME_ID_ARGS=${GAME_ID_ARGS}
        - GAME_PARAMS=${GAME_PARAMS}
    image: motortowndedicated
    container_name: motortowndedicated
    ports:
      - "27015:27015"
      - "27015:27015/UDP"
      - "7777:7777"
      - "7777:7777/UDP"
      - "8998:8080"
    environment:
      - USERNAME=${STEAM_USERNAME}
      - PASSWRD=${STEAM_PASSWORD}
      - GAME_ID=${GAME_ID}
      - GAME_ID_ARGS=${GAME_ID_ARGS}
      - GAME_PARAMS=${GAME_PARAMS}
    volumes:
      - /mnt/user/appdata/motortowndedicated:/serverdata/serverfiles
      - /mnt/user/appdata/steamcmd:/serverdata/steamcmd
